const state={gateway:sessionStorage.getItem("aether.gateway.url")||window.location.origin,token:sessionStorage.getItem("aether.operator.token")||"",snapshot:null};
const $=id=>document.getElementById(id);const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const tone=v=>{v=String(v||"");if(["completed","approved","verified"].includes(v))return"success";if(["failed","rejected","cancelled","stopped"].includes(v))return"danger";if(["waiting-approval","paused","review-required","realized"].includes(v))return"warning";return"neutral"};
function toast(msg,error=false){const n=$("toast");n.textContent=msg;n.style.borderColor=error?"rgba(255,107,122,.5)":"rgba(85,214,190,.4)";n.classList.add("visible");clearTimeout(n._t);n._t=setTimeout(()=>n.classList.remove("visible"),3000)}
async function request(path,options={}){if(!state.token)throw new Error("Operator token is required");const headers={"X-Aether-Operator-Token":state.token,...(options.headers||{})};if(options.body)headers["Content-Type"]="application/json";const r=await fetch(`${state.gateway.replace(/\/$/,"")}${path}`,{...options,headers});const t=await r.text();let p={};try{p=t?JSON.parse(t):{}}catch{p={detail:t}}if(!r.ok)throw new Error(p.detail||`${r.status}`);return p}
function money(v){return `$${Number(v||0).toFixed(2)}`}
function render(s){state.snapshot=s;$("connection").className="badge success";$("connection").textContent="Connected";const c=s.status?.by_status||{};$("summary").innerHTML=[["Opportunities",s.status?.briefs||0],["Missions",s.status?.missions||0],["Awaiting review",c["review-required"]||0],["Waiting approval",c["waiting-approval"]||0],["Completed",c.completed||0]].map(([l,v])=>`<div class="summary-card"><span class="muted">${esc(l)}</span><strong>${esc(v)}</strong></div>`).join("");
$("briefs").innerHTML=(s.opportunities||[]).map(b=>`<div class="item"><div class="item-row"><div><div class="item-title">${esc(b.title)}</div><div class="detail">${esc(b.problem_statement)}</div></div><span class="badge ${b.blockers?.length?"warning":"success"}">${b.blockers?.length?"blocked":"reviewable"}</span></div><div class="metric"><span>${esc(b.lane)}</span><span>EV ${money(b.expected_net_value_usd)}</span><span>${esc(b.independent_support_count)} independent sources</span><span>${esc(b.contradiction_evidence_ids?.length||0)} contradictions</span></div></div>`).join("")||'<div class="empty">No opportunity briefs.</div>';
let claimed=0,realized=0,verified=0;$("missions").innerHTML=(s.missions||[]).map(m=>{const p=m.plan,b=m.brief,o=m.outcome||{};claimed+=Number(o.claimed_value_usd||0);realized+=Number(o.realized_revenue_usd||0);verified+=Number(o.verified_revenue_usd||0);const buttons=m.status==="review-required"?`<button class="button small primary" data-act="approve" data-id="${esc(p.mission_id)}">Approve</button>`:["approved","paused","waiting-approval","running"].includes(m.status)?`<button class="button small primary" data-act="run" data-id="${esc(p.mission_id)}">Run / Resume</button><button class="button small secondary" data-act="pause" data-id="${esc(p.mission_id)}">Pause</button>`:"";return `<div class="item"><div class="item-row"><div><div class="item-title">${esc(p.objective)}</div><div class="detail">${esc(p.northstar_alignment)}</div></div><span class="badge ${tone(m.status)}">${esc(m.status)}</span></div><div class="metric"><span>${esc(p.lane)}</span><span>${esc(p.steps.length)} steps</span><span>Budget ${money(p.budget.max_cost_usd)}</span><span>Verified ${money(o.verified_revenue_usd)}</span></div><div class="item-actions">${buttons}</div></div>`}).join("")||'<div class="empty">No missions.</div>';
$("value").innerHTML=[["Claimed value",claimed,"Claims are hypotheses, not revenue."],["Realized revenue",realized,"Backed by external evidence."],["Verified revenue",verified,"Founder/operator verified evidence."]].map(([l,v,d])=>`<div class="value-card"><span class="muted">${esc(l)}</span><strong>${money(v)}</strong><div class="detail">${esc(d)}</div></div>`).join("")}
async function load(){const s=await request("/api/mission-operations/console");render(s)}
$("connect").onclick=async()=>{state.gateway=$("gateway").value.trim()||window.location.origin;state.token=$("token").value;sessionStorage.setItem("aether.gateway.url",state.gateway);sessionStorage.setItem("aether.operator.token",state.token);try{await load();toast("Connected") }catch(e){toast(e.message,true)}};$("refresh").onclick=()=>load().catch(e=>toast(e.message,true));document.body.addEventListener("click",async e=>{const b=e.target.closest("button[data-act]");if(!b)return;b.disabled=true;try{const id=encodeURIComponent(b.dataset.id);if(b.dataset.act==="approve")await request(`/api/missions/${id}/approve`,{method:"POST",body:JSON.stringify({reason:"Reviewed from AionUi mission console"})});if(b.dataset.act==="run")await request(`/api/missions/${id}/run`,{method:"POST",body:JSON.stringify({maximum_steps:5})});if(b.dataset.act==="pause")await request(`/api/missions/${id}/pause`,{method:"POST",body:JSON.stringify({reason:"Paused from AionUi mission console"})});await load();toast("Mission operation completed")}catch(err){toast(err.message,true)}finally{b.disabled=false}});$("gateway").value=state.gateway;$("token").value=state.token;if(state.token)load().catch(()=>{});
