"""Project Aether mind state into aether-agent body files (one-way)."""
from __future__ import annotations
from pathlib import Path
from typing import List, Optional

from aether.dna.loader import DNALoader


HEADER = (
    "<!-- AUTO-GENERATED by Aether. DO NOT EDIT BY HAND. -->\n"
    "<!-- Source of truth: aether-core DNA + SelfModel. -->\n\n"
)


def project_soul(body_home: Path, dna: Optional[DNALoader] = None) -> Path:
    dna = dna or DNALoader()
    identity = dna.load_identity()
    genome = dna.load_genome()
    ns = dna.load_north_star()
    name = identity.get("identity", {}).get("name", "Aether")
    mission = identity.get("mission", {}).get("primary", "")
    ns_stmt = ns.get("north_star", {}).get("statement", "").strip()
    principles = ns.get("sacred_principles", [])
    sp_lines = "\n".join(
        f"- {p.get('name')}: {p.get('statement')}" for p in principles if isinstance(p, dict)
    )
    # Compact genome excerpt (first 40 lines) — body prompt budget
    genome_excerpt = "\n".join(genome.splitlines()[:40])
    text = (
        f"{HEADER}"
        f"# SOUL — {name}\n\n"
        f"## Mission\n{mission}\n\n"
        f"## North Star\n{ns_stmt}\n\n"
        f"## Sacred Principles\n{sp_lines}\n\n"
        f"## Genome (excerpt)\n```\n{genome_excerpt}\n```\n"
    )
    path = Path(body_home) / "SOUL.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def project_memory(body_home: Path, facts: Optional[List[str]] = None) -> Path:
    """Operational facts only. Never project beliefs."""
    facts = facts or []
    lines = [HEADER, "# MEMORY — operational (Aether projection)\n", "## Facts\n"]
    for f in facts[:40]:
        lines.append(f"- {f}\n")
    lines.append("\n<!-- no beliefs projected — different class -->\n")
    path = Path(body_home) / "MEMORY.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(lines), encoding="utf-8")
    return path
